version: '3.8'

services:
  backend:
    build: ./server
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env

  frontend:
    build: ./client
    restart: always
    ports:
      - "80:80"
      - "443:443" # OPEN PORT 443 FOR HTTPS
    depends_on:
      - backend 
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro # MOUNT THE SSL CERTIFICATES FROM THE HOST